from pptx import Presentation
import os

async def generate_ppt(session_id: str, topic: str, findings: list[dict]) -> str:
    output_path = f"./reports/presentation_{session_id}.pptx"
    os.makedirs("./reports", exist_ok=True)
    
    prs = Presentation()
    
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = f"Research Report:\n{topic}"
    subtitle.text = "Generated by Autonomous Research Agents"
    
    bullet_slide_layout = prs.slide_layouts[1]
    for i, finding in enumerate(findings):
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = f"Finding {i+1}"
        tf = body_shape.text_frame
        
        content = finding.get("content", "")
        if len(content) > 200:
            content = content[:197] + "..."
            
        tf.text = content
        
    prs.save(output_path)
    return output_path
